version: '2'
services:
  test:
    image: anaisurlichs/example-selenium-test:1.0.0
    depends_on:
      - selenium
    volumes:
      - /dev/shm:/dev/shm
    environment:
      GITHUB_ACCOUNT: $GITHUB_ACCOUNT
      GITHUB_PASSWORD: $GITHUB_PASSWORD
      URL: $URL
  selenium:
    image: selenium/standalone-chrome:4.0.0
    ports:
      - 4444:4444